// Directory data with names, URLs, character limits, and industry relevance
export const DIRECTORIES = [
  {
    id: 'google-business-profile',
    name: 'Google Business Profile',
    url: 'https://business.google.com/',
    charLimit: 750,
    industries: ['all'],
    icon: 'search',
  },
  {
    id: 'yelp',
    name: 'Yelp',
    url: 'https://biz.yelp.com/',
    charLimit: 5000,
    industries: ['all'],
    icon: 'star',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    url: 'https://www.facebook.com/pages/create/',
    charLimit: 255,
    industries: ['all'],
    icon: 'users',
  },
  {
    id: 'apple-maps',
    name: 'Apple Maps',
    url: 'https://mapsconnect.apple.com/',
    charLimit: 500,
    industries: ['all'],
    icon: 'map',
  },
  {
    id: 'bing-places',
    name: 'Bing Places',
    url: 'https://www.bingplaces.com/',
    charLimit: 750,
    industries: ['all'],
    icon: 'search',
  },
  {
    id: 'nextdoor',
    name: 'Nextdoor',
    url: 'https://business.nextdoor.com/',
    charLimit: 300,
    industries: ['all'],
    icon: 'home',
  },
  {
    id: 'bbb',
    name: 'Better Business Bureau',
    url: 'https://www.bbb.org/get-listed',
    charLimit: 1000,
    industries: ['all'],
    icon: 'shield',
  },
  {
    id: 'yellow-pages',
    name: 'Yellow Pages',
    url: 'https://adsolutions.yp.com/',
    charLimit: 1000,
    industries: ['all'],
    icon: 'book',
  },
  {
    id: 'angi',
    name: 'Angi',
    url: 'https://www.angi.com/pro/',
    charLimit: 1000,
    industries: ['home-services', 'construction', 'landscaping', 'cleaning', 'plumbing', 'electrical', 'hvac', 'roofing'],
    icon: 'wrench',
  },
  {
    id: 'thumbtack',
    name: 'Thumbtack',
    url: 'https://www.thumbtack.com/pro/',
    charLimit: 500,
    industries: ['home-services', 'construction', 'landscaping', 'cleaning', 'plumbing', 'electrical', 'hvac', 'photography', 'events'],
    icon: 'pin',
  },
  {
    id: 'homeadvisor',
    name: 'HomeAdvisor',
    url: 'https://pro.homeadvisor.com/',
    charLimit: 750,
    industries: ['home-services', 'construction', 'landscaping', 'cleaning', 'plumbing', 'electrical', 'hvac', 'roofing'],
    icon: 'home',
  },
  {
    id: 'healthgrades',
    name: 'Healthgrades',
    url: 'https://update.healthgrades.com/',
    charLimit: 1000,
    industries: ['medical', 'dental', 'healthcare'],
    icon: 'heart',
  },
  {
    id: 'avvo',
    name: 'Avvo',
    url: 'https://www.avvo.com/for-lawyers',
    charLimit: 2000,
    industries: ['legal'],
    icon: 'scale',
  },
  {
    id: 'tripadvisor',
    name: 'TripAdvisor',
    url: 'https://www.tripadvisor.com/Owners',
    charLimit: 1000,
    industries: ['hospitality', 'restaurant', 'tourism', 'hotel'],
    icon: 'globe',
  },
  {
    id: 'opentable',
    name: 'OpenTable',
    url: 'https://restaurant.opentable.com/',
    charLimit: 500,
    industries: ['restaurant', 'food-beverage'],
    icon: 'utensils',
  },
  {
    id: 'houzz',
    name: 'Houzz',
    url: 'https://www.houzz.com/professionals',
    charLimit: 2000,
    industries: ['home-services', 'construction', 'landscaping', 'interior-design', 'architecture'],
    icon: 'home',
  },
  {
    id: 'carfax',
    name: 'CarFax',
    url: 'https://repairpal.com/shop/registration',
    charLimit: 500,
    industries: ['automotive'],
    icon: 'car',
  },
  {
    id: 'vitals',
    name: 'Vitals',
    url: 'https://www.vitals.com/providers',
    charLimit: 1000,
    industries: ['medical', 'dental', 'healthcare'],
    icon: 'heart',
  },
  {
    id: 'martindale',
    name: 'Martindale',
    url: 'https://www.martindale.com/attorneys/',
    charLimit: 2000,
    industries: ['legal'],
    icon: 'scale',
  },
  {
    id: 'weddingwire',
    name: 'WeddingWire',
    url: 'https://www.weddingwire.com/vendor-signup',
    charLimit: 1000,
    industries: ['events', 'photography', 'catering', 'florist'],
    icon: 'heart',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    url: 'https://www.linkedin.com/company/setup/new/',
    charLimit: 2000,
    industries: ['all'],
    icon: 'briefcase',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    url: 'https://www.instagram.com/',
    charLimit: 150,
    industries: ['all'],
    icon: 'camera',
  },
];

export const BUSINESS_TYPES = [
  { value: 'home-services', label: 'Home Services' },
  { value: 'restaurant', label: 'Restaurant / Food & Beverage' },
  { value: 'medical', label: 'Medical / Healthcare' },
  { value: 'dental', label: 'Dental' },
  { value: 'legal', label: 'Legal Services' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'construction', label: 'Construction / Contracting' },
  { value: 'landscaping', label: 'Landscaping / Lawn Care' },
  { value: 'cleaning', label: 'Cleaning Services' },
  { value: 'plumbing', label: 'Plumbing' },
  { value: 'electrical', label: 'Electrical' },
  { value: 'hvac', label: 'HVAC' },
  { value: 'roofing', label: 'Roofing' },
  { value: 'real-estate', label: 'Real Estate' },
  { value: 'photography', label: 'Photography' },
  { value: 'hospitality', label: 'Hospitality / Hotel' },
  { value: 'tourism', label: 'Tourism / Travel' },
  { value: 'retail', label: 'Retail' },
  { value: 'fitness', label: 'Fitness / Wellness' },
  { value: 'salon', label: 'Salon / Spa / Beauty' },
  { value: 'events', label: 'Events / Wedding' },
  { value: 'interior-design', label: 'Interior Design' },
  { value: 'architecture', label: 'Architecture' },
  { value: 'accounting', label: 'Accounting / Financial' },
  { value: 'insurance', label: 'Insurance' },
  { value: 'pet-services', label: 'Pet Services / Veterinary' },
  { value: 'education', label: 'Education / Tutoring' },
  { value: 'technology', label: 'Technology / IT Services' },
  { value: 'marketing', label: 'Marketing / Advertising' },
  { value: 'other', label: 'Other' },
];

export const US_STATES = [
  'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA',
  'HI','ID','IL','IN','IA','KS','KY','LA','ME','MD',
  'MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ',
  'NM','NY','NC','ND','OH','OK','OR','PA','RI','SC',
  'SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','DC',
];

export function getRelevantDirectories(businessType) {
  return DIRECTORIES.filter(d =>
    d.industries.includes('all') || d.industries.includes(businessType)
  );
}
